data:
  test: 
    images-ubyte: "data/raw/t10k-images.idx3-ubyte"
    labels-ubyte: "data/raw/t10k-labels.idx1-ubyte"
  train:
    images-ubyte: "data/raw/train-images.idx3-ubyte"
    labels-ubyte: "data/raw/train-labels.idx1-ubyte"